package fr.inrae.act.bagap.chloe.analysis;

public enum ChloeAnalysisType {

	MAP, ENTITY, GRID, SLIDING, SELECTED, 
	DISTANCE, CLUSTER,
	COMBINE, SEARCHANDREPLACE, CLASSIFICATION,
	RASTER_FROM_CSV, RASTER_FROM_SHAPEFILE;
}
